name: Generate Changelog
on:
  push:
    tags:
      - 'v*'
jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate changelog
      run: |
        chmod +x ./runner.sh
        ./runner.sh
      env:
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      shell: bash
    - name: Commit and push changes
      run: |
        git config --global user.name "ShaileshKumar97"
        git config --global user.email "kumar.shailesh1597@gmail.com"
        git checkout master
        git add CHANGELOG.md
        git commit -m "Generate changelog"
        git push
