name: Generate Changelog
on:
  push:
    branches:
      - 'master'
jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Generate changelog
      run: |
        bash runner.sh
    - name: Commit and push changes
      run: |
        git config --global user.name "ShaileshKumar97"
        git config --global user.email "kumar.shailesh1597@gmail.com"
        git add changelog.md
        git commit -m "Generate changelog"
        git push
