name: Generate Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change this to the version of Python you want to use

    # - name: Install dependencies
    #   run: pip install -r requirements.txt  # Change this to the path of your requirements file, if applicable

    - name: Get previous tag
      run: |
        PREV_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
        echo "PREV_TAG=${PREV_TAG}" >> $GITHUB_ENV

    - name: Generate changelog
      run: |
        PREV_TAG=${{ env.PREV_TAG }}
        echo "Bug Fixes:" > changelog.md
        git log ${PREV_TAG}..HEAD --grep="^fix" --pretty=format:"%C(auto)- %s %h" >> changelog.md
        echo "" >> changelog.md
        echo "Features:" >> changelog.md
        git log ${PREV_TAG}..HEAD --grep="^chore" --pretty=format:"%C(auto)- %s %h" >> changelog.md
        echo "" >> changelog.md
        echo "Merged Pull Requests:" >> changelog.md
        git log ${PREV_TAG}..HEAD --grep="^Merge pull request" --pretty=format:"%C(auto)- %s %h" >> changelog.md

    - name: Commit and push changes
      run: |
        git config user.name "ShaileshKumar97"
        git config user.email "kumar.shailesh1597@gmail.com"
        git add changelog.md
        git commit -m "Generate changelog"
        git push
