name: Generate Changelog
on:
  push:
    tags:
      - 'v*'
jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate changelog
      run: |
        chmod +x ./runner.sh
        ./runner.sh
    - name: Set up environment variable
      run: echo "CURRENT_TAG=${{ env.CURRENT_TAG }}" >> $GITHUB_ENV
      env:
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      shell: bash
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "noreply@github.com"
        git checkout master
        git add CHANGELOG.md
        git commit -m "chore(release): release ${{ env.CURRENT_TAG }}#v"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
